version: 0.2

env:
  variables:
    REPOSITORY_URI: 339713037827.dkr.ecr.ap-south-1.amazonaws.com/javatechie-registry

phases:
  pre_build:
    commands:
      - echo "Cleaning and packaging with Maven"
      - mvn clean install
      - echo "Logging in to Amazon ECR"
      - aws --version
      - aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image"
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images"
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Generating imagedefinitions.json for ECS"
      - printf '[{"name":"javatechie-registry","imageUri":"%s"}]' \
        $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Image definitions file content:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar