services:
  app:
    build: .
    container_name: Snapbuy-App
    ports:
      - "8080:8080"
    networks:
      s-network:
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    container_name: Snapbuy-SQL
    environment:
      MYSQL_ROOT_PASSWORD: 'RishabhGupta&2005@'
      MYSQL_DATABASE: SnapBuy
    ports:
      - "3307:3306"
    networks:
      s-network:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pRishabhGupta&2005@"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  s-network:
    driver: bridge111111111111111111