export const products = [
  {
    id: 1,
    name: "iPhone 17 Air",
    brand: "Apple",
    price: 89900,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "The latest iPhone with advanced AI features, a stunning display, and all-day battery life. Experience the power of Apple's newest A18 chip and an improved camera system.",
    rating: 4.8,
    reviews: 245,
    category: "electronics",
    stock: 15,
    variants: [
      { id: 1, type: "color", name: "Space Black", value: "#1a1a1a", available: true },
      { id: 2, type: "color", name: "Silver", value: "#c0c0c0", available: true },
      { id: 3, type: "color", name: "Gold", value: "#ffd700", available: false },
      { id: 4, type: "storage", name: "128GB", value: "128GB", priceModifier: 0, available: true },
      { id: 5, type: "storage", name: "256GB", value: "256GB", priceModifier: 10000, available: true },
      { id: 6, type: "storage", name: "512GB", value: "512GB", priceModifier: 20000, available: true },
    ],
  },
  {
    id: 2,
    name: "Dell XPS 17 9700",
    brand: "Dell",
    price: 204114,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "A premium laptop with a stunning 17-inch 4K UHD+ display, powerful Intel Core i9 processor, NVIDIA GeForce RTX graphics, and exceptional build quality for professionals and creators.",
    rating: 4.6,
    reviews: 128,
    category: "electronics",
    stock: 8,
    variants: [
      { id: 7, type: "color", name: "Platinum Silver", value: "#e5e5e5", available: true },
      { id: 8, type: "color", name: "Frost White", value: "#f8f8f8", available: true },
      { id: 9, type: "ram", name: "16GB", value: "16GB", priceModifier: 0, available: true },
      { id: 10, type: "ram", name: "32GB", value: "32GB", priceModifier: 25000, available: true },
    ],
  },
  {
    id: 3,
    name: "Apple M4 MacBook Air",
    brand: "Apple",
    price: 99899,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "The thinnest, lightest notebook, completely transformed by the Apple M4 chip. With up to 18 hours of battery life, a stunning Retina display, and silent, fanless design.",
    rating: 4.9,
    reviews: 312,
    category: "electronics",
    stock: 22,
    variants: [
      { id: 11, type: "color", name: "Space Gray", value: "#8e8e93", available: true },
      { id: 12, type: "color", name: "Silver", value: "#c0c0c0", available: true },
      { id: 13, type: "color", name: "Gold", value: "#ffd700", available: true },
      { id: 14, type: "color", name: "Midnight", value: "#191970", available: false },
    ],
  },
  {
    id: 4,
    name: "Levi's 511 Brutus Slim Fit Denim Jeans",
    brand: "Levi",
    price: 3299,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Classic slim fit jeans with a modern look. These versatile jeans feature a comfortable stretch denim fabric, classic 5-pocket styling, and a timeless design that pairs with anything.",
    rating: 4.5,
    reviews: 523,
    category: "clothing",
    stock: 45,
    variants: [
      { id: 15, type: "size", name: "28", value: "28", available: true },
      { id: 16, type: "size", name: "30", value: "30", available: true },
      { id: 17, type: "size", name: "32", value: "32", available: true },
      { id: 18, type: "size", name: "34", value: "34", available: false },
      { id: 19, type: "size", name: "36", value: "36", available: true },
      { id: 20, type: "color", name: "Dark Blue", value: "#1e3a8a", available: true },
      { id: 21, type: "color", name: "Light Blue", value: "#3b82f6", available: true },
      { id: 22, type: "color", name: "Black", value: "#000000", available: true },
    ],
  },
  {
    id: 5,
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    price: 24990,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Industry-leading noise cancellation with two processors and eight microphones. Crystal clear hands-free calling and up to 30 hours of battery life with quick charging.",
    rating: 4.7,
    reviews: 189,
    category: "electronics",
    stock: 0,
    variants: [
      { id: 23, type: "color", name: "Black", value: "#000000", available: false },
      { id: 24, type: "color", name: "Silver", value: "#c0c0c0", available: false },
    ],
  },
  {
    id: 6,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 124999,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "The ultimate smartphone experience with a 6.8-inch Dynamic AMOLED display, 200MP camera system, S Pen functionality, and powerful AI features powered by Snapdragon 8 Gen 3.",
    rating: 4.6,
    reviews: 276,
    category: "electronics",
    stock: 3,
    variants: [
      { id: 25, type: "color", name: "Titanium Black", value: "#2c2c2c", available: true },
      { id: 26, type: "color", name: "Titanium Gray", value: "#808080", available: true },
      { id: 27, type: "color", name: "Titanium Violet", value: "#8a2be2", available: false },
      { id: 28, type: "storage", name: "256GB", value: "256GB", priceModifier: 0, available: true },
      { id: 29, type: "storage", name: "512GB", value: "512GB", priceModifier: 15000, available: true },
    ],
  },
  {
    id: 7,
    name: "Nike Air Zoom Pegasus 40",
    brand: "Nike",
    price: 9995,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "The iconic running shoe returns with responsive cushioning, breathable mesh upper, and versatile design suitable for everyday runs and training sessions.",
    rating: 4.4,
    reviews: 412,
    category: "clothing",
    stock: 28,
    variants: [
      { id: 30, type: "size", name: "7", value: "7", available: true },
      { id: 31, type: "size", name: "8", value: "8", available: true },
      { id: 32, type: "size", name: "9", value: "9", available: true },
      { id: 33, type: "size", name: "10", value: "10", available: false },
      { id: 34, type: "size", name: "11", value: "11", available: true },
      { id: 35, type: "color", name: "White/Black", value: "#ffffff", available: true },
      { id: 36, type: "color", name: "Black/White", value: "#000000", available: true },
      { id: 37, type: "color", name: "Blue/Orange", value: "#1e40af", available: true },
    ],
  },
  {
    id: 8,
    name: "Canon EOS R6 Mark II",
    brand: "Canon",
    price: 219990,
    image: "/placeholder.svg?height=400&width=400",
    description:
      "Professional-grade mirrorless camera with 24.2MP full-frame CMOS sensor, 4K60p video recording, in-body image stabilization, and advanced autofocus with subject tracking.",
    rating: 4.8,
    reviews: 97,
    category: "electronics",
    stock: 12,
    variants: [
      { id: 38, type: "kit", name: "Body Only", value: "body", priceModifier: 0, available: true },
      { id: 39, type: "kit", name: "24-105mm Kit", value: "kit1", priceModifier: 45000, available: true },
      { id: 40, type: "kit", name: "24-70mm Kit", value: "kit2", priceModifier: 65000, available: false },
    ],
  },
]
