spring.application.name=SnapBuy

# Set active profile
spring.profiles.active=prod
server.port=${PORT:8080}

# Gemini Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
spring.ai.google.genai.chat.options.max-tokens=2048
spring.ai.google.genai.chat.options.temperature=0.5
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${app.base.url}/api/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile,openid

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.success.url=${app.base.url}/payment/success
stripe.cancel.url=${app.base.url}/payment/cancel

# Application Settings
app.base.url=${APP_BASE_URL:http://localhost:8080}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
app.auth.success-redirect=${app.frontend.url}/oauth2/callback
app.auth.failure-redirect=${app.frontend.url}/login?error=oauth_failed

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=1296000000

# OTP Configuration
otp.expiration-ms=300000
otp.cleanup-rate-ms=60000
otp.length=6
ott.token.expiry.seconds=300
ott.cleanup-rate-ms=300000

# Mail Configuration
spring.mail.from=${MAIL_USERNAME}
brevo.api.key=${BREVO_API_KEY}

# MongoDB Atlas Vector Search Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=snapbuy
spring.ai.vectorstore.mongodb.collection-name=snapbuy_vectors
spring.ai.vectorstore.mongodb.initialize-schema=false
management.health.mongo.enabled=false

# Swagger / OpenAPI Configuration
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Enable response compression
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain,text/css,text/javascript,application/javascript,application/x-javascript,application/octet-stream
server.compression.min-response-size=1024

# Logging Configuration
spring.output.ansi.enabled=always
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n